# generated by Neptune Namespaces v3.x.x
# file: Art.Models/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Models', class Models extends Neptune.PackageNamespace
  @version: require('../../package.json').version
