# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Models/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Models', class Models extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
